services:
  postgres:
    image: postgres:16-alpine
    container_name: jedistore-postgres
    environment:
      POSTGRES_DB: jedistore
      POSTGRES_USER: jedistore
      POSTGRES_PASSWORD: jedistore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jedistore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jedistore -d jedistore"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jedistore-api
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: jedistore
      SPRING_DATASOURCE_PASSWORD: jedistore
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jedistore-network

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: jedistore-mcp-server
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: jedistore
      SPRING_DATASOURCE_PASSWORD: jedistore
    depends_on:
      postgres:
        condition: service_healthy
      llm:
        condition: service_started
    networks:
      - jedistore-network

  orchestrateur:
    build:
      context: ./orchestrateur
      dockerfile: Dockerfile
    container_name: jedistore-orchestrateur
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mcp-server
      - llm
    networks:
      - jedistore-network
  llm:
    image: ollama/ollama
    container_name: ollama_ministral
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull ministral-3:3b && wait"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - jedistore-network

  jedi-helpdesk:
    build:
      context: ./jedi-helpdesk
      dockerfile: Dockerfile
    container_name: jedistore-helpdesk
    ports:
      - "5173:80"
    depends_on:
      - orchestrateur
      - keycloak
    networks:
      - jedistore-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    ports:
      - "8888:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:8888
      KC_HOSTNAME_ADMIN_URL: http://localhost:8888
    #entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--verbose"]
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--verbose"]
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-coruscant.json:/opt/keycloak/data/import/realm-coruscant.json
    networks:
      - jedistore-network

volumes:
  postgres_data:
  keycloak_data:
  ollama_data:

networks:
  jedistore-network:
    driver: bridge
