server:
  port: 8080

spring:
  application:
    name: poke-store-orchestrateur
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: ministral-3:3b
    mcp:
      client:
        type: ASYNC
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            mcp-server:
              url: http://localhost:8081

