server:
  port: 8081

spring:
  application:
    name: poke-store-mcp-server
  ai:
    mcp:
      server:
        protocol: streamable
        name: poke-store-mcp-server
        version: 1.0.0
        type: SYNC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/pokestore
logging:
  level:
    org:
      springframework:
        ai:
          mcp: DEBUG
